ReimburseSystem.Web/Controllers/WidgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReimburseSystem.Common.Cookie;
using ReimburseSystem.Common.Session;
using ReimburseSystem.Common.Encryption;
using ReimburseSystem.Common;

namespace ReimburseSystem.Web.Controllers
{
    public partial class WidgetController : Controller
    {
        //
        // GET: /Widget/

        public virtual ActionResult Index()
        {
            if (Request.Cookies["Login"] == null || Request.Cookies["Role"] == null)
            {
                return RedirectToAction(MVC.Users.Login());
            }
            return View();
        }

        public virtual ActionResult Navbar()
        {
            string username = string.Empty;
            if (Request.Cookies["Login"] != null)
            {
                
            }

            ViewData.Model = username;
            return PartialView();
        }

        public virtual ActionResult Sidebar()
        {

            if (Request.Cookies["Role"] != null) {
                ViewBag.Role = Request.Cookies["Role"].Value;

            }
            return PartialView();
               
        }

        [HttpPost]
        public void setCookieClientID(Guid ID)
        {
            CookieManager.Add(CookieManager.CLIENT_ID, ID.ToString(), true, false);

        }

    }
}

ReimburseSystem.Web/Views/Widget/Navbar.cshtml
@model string
<!-- navbar -->
<div class="navbar navbar-inverse">

    <div class="navbar-inner" style="height:66px;">
        @{Html.RenderAction(MVC.Widget.Sidebar());}
        <button type="button" class="btn btn-navbar visible-phone" id="menu-toggler">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <a cremotgelass="brand" href="@Url.Action(MVC.Users.Index())">
            <img src="@Links.Assets.Img.logo_png" style="position: absolute; top: -2px; z-index: 99; left:0;">
        </a>

        <ul class="nav pull-right">
            @*<li><a href="@Url.Action(MVC.Admin.Account.Personal())">Personal info</a></li>*@
            <li></li>
            <li><a href="@Url.Action(MVC.Users.LogOut())">Log Out</a></li>
        </ul>

        <ul class="nav pull-right">
            @*<li><a href="@Url.Action(MVC.Admin.Account.Personal())">Personal info</a></li>*@
            <li></li>
            <li><span class="navbar-username">Welcome, @Model</span></li>
        </ul>

       
    </div>



</div>
  <script type="text/javascript">
       

        $(document).ready(function () {
           
          
        });
    </script>

ReimburseSystem.Web/Views/Widget/Sidebar.cshtml
@{
    string urlReq = HttpContext.Current.Request.Url.AbsoluteUri.ToLower() + "/";
    string role = ViewBag.Role;
}
@using ReimburseSystem.Common


<!-- begin sidebar nav -->


<ul class="nav">

    <li class="nav-header">Navigation</li>

    <li class="has-sub active">
        <a href="javascript:;">
            <i class="fa fa-suitcase"></i>
            <b class="caret pull-right"></b>
            <span>Master</span>
        </a>
        <ul class="sub-menu">

            @if (urlReq.ToLower().Contains("users"))
            {
                <li class="active"><a href="@Url.Action(MVC.Users.IndexTable()))">User</a></li>
            }
            else
            {
                <li><a href="@Url.Action(MVC.Users.IndexTable()))">User</a></li>
            }


            @if (role == Constant.UserRole.Administrator)
            {
                if (urlReq.ToLower().Contains("reimbursetype"))
                {
                    <li class="active"><a href="">Reimburse Type</a></li>
                }
                else
                {
                    <li><a href="">Reimburse Type</a></li>
                }

                if (urlReq.ToLower().Contains("reimbursebudget"))
                {
                    <li class="active"><a href="">Reimburse Budget</a></li>
                }
                else
                {
                    <li><a href="">Reimburse Budget</a></li>
                }
            }

        </ul>

        <a href="javascript:;">
            <i class="fa fa-suitcase"></i>
            <b class="caret pull-right"></b>
            <span>Main</span>
        </a>
        <ul class="sub-menu">

            @if (urlReq.ToLower().Contains("reimburse"))
            {
                <li class="active"><a href="@Url.Action(MVC.Reimburse.Index())">Reimburse</a></li>
            }
            else
            {
                <li><a href="@Url.Action(MVC.Reimburse.Index())">Reimburse</a></li>
            }

        </ul>


        <a href="javascript:;">
            <i class="fa fa-suitcase"></i>
            <b class="caret pull-right"></b>
            <span>Report</span>
        </a>
        <ul class="sub-menu">
            <li class="active"><a href="">Reimburse Report</a></li>
            @*@if (urlReq.ToLower().Contains("report"))
        {
            <li class="active"><a href="@Url.Action(MVC.Rent.Reporting())">Rent Report</a></li>
        }
        else
        {
            <li><a href="@Url.Action(MVC.Rent.Reporting())">Rent Report</a></li>
        }*@
        </ul>
    </li>

    <!-- begin sidebar minify button -->
    <li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
    <!-- end sidebar minify button -->
</ul>
<!-- end sidebar nav -->

<script>
    function selectOption() {
        var id = document.getElementById("list-clients").options[document.getElementById("list-clients").selectedIndex].id;
        $.ajax({
            url: '@Url.Action("setCookieClientID", "Widget")'+'?ID=' + id,
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            processData: false,
            success: function (result) {
                location.reload();
            },
            error: function (err, ex, msg) {
                alert("error set cookie clientID");
            }
        });
    }
</script>